---
dist: xenial

sudo: required

services:
  - docker

language: python
python:
  - "3.7"

before_install:
#  - docker pull centos/systemd

script:
  - which python
  - make travis

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
